In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('pokemon_data.csv')
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [6]:
df.loc[df['Type 1']=='Grass']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False

In [8]:
df.loc[(df['Type 1']=='Grass')&(df['Type 2']=='Poison')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False

In [10]:
df.loc[(df['Type 1']=='Fire')&(df['Type 2']=='Flying')&(df['Attack']>=90)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True

In [12]:
df.loc[(df['Type 1']=='Water')&(df['Type 2']=='Flying')&(df['Defense']>=80)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
302,279,Pelipper,Water,Flying,60,50,100,85,70,65,3,False

In [16]:
df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,105,125,100,60,100,100,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,106,150,70,194,120,140,1,True
168,154,Meganium,Grass,NaN,80,82,100,83,100,80,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,90,95,105,165,110,45,2,False
224,208,SteelixMega Steelix,Steel,Ground,75,125,230,55,95,30,2,False
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,75,90,90,140,90,115,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,70,110,75,145,85,145,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
283,260,SwampertMega Swampert,Water,Ground,100,150,110,95,110,70,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,68,85,65,165,135,100,3,False
327,302,SableyeMega Sableye,Dark,Ghost,50,85,125,85,115,20,3,False
329,303,MawileMega Mawile,Steel,Fairy,50,105,125,55,95,50,3,False
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,60,100,85,80,85,100,3,False
339,310,ManectricMega Manectric,Electric,NaN,70,75,80,135,80,135,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,70,140,70,110,65,105,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,75,110,110,110,105,80,3,False
387,354,BanetteMega Banette,Ghost,NaN,64,165,75,93,83,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
397,362,GlalieMega Glalie,Ice,NaN,80,120,80,120,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,65,136,94,54,96,135,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,108,170,115,120,95,92,4,False
498,448,LucarioMega Lucario,Fighting,Steel,70,145,88,140,70,112,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,4,False
591,531,AudinoMega Audino,Normal,Fairy,103,60,126,80,126,50,5,False
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True

In [15]:
df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [20]:
import re
df.loc[df['Name'].str.contains('pi', regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
13,10,Caterpie,Bug,NaN,45,30,35,20,20,45,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,2,False
189,175,Togepi,Fairy,NaN,35,20,65,40,65,20,2,False
202,187,Hoppip,Grass,Flying,35,35,40,35,55,50,2,False
266,247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,False
345,316,Gulpin,Poison,NaN,70,43,53,43,53,40,3,False
357,326,Grumpig,Psychic,NaN,80,45,65,90,110,80,3,False
358,327,Spinda,Normal,NaN,60,60,60,60,60,60,3,False
359,328,Trapinch,Ground,NaN,45,100,45,45,45,10,3,False
390,357,Tropius,Grass,Flying,99,68,83,72,87,51,3,False
463,416,Vespiquen,Bug,Flying,70,80,102,80,102,40,4,False
488,440,Happiny,Normal,NaN,100,5,5,15,65,30,4,False
490,442,Spiritomb,Ghost,Dark,50,92,108,92,108,35,4,False
501,451,Skorupi,Poison,Bug,40,50,90,30,55,65,4,False
502,452,Drapion,Poison,Dark,70,90,110,60,75,95,4,False
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
596,536,Palpitoad,Water,Ground,75,65,55,65,55,69,5,False
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False

In [22]:
df.loc[df['Name'].str.contains('pi',flags=re.I, regex=True)]#no longer case-sensitive

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False

In [23]:
df.loc[df['Name'].str.contains('^pi',flags=re.I, regex=True)]#starts with pi

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False

In [24]:
df.loc[df['Name'].str.contains('ot$',flags=re.I, regex=True)]#end with 'ot'

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
177,163,Hoothoot,Normal,Flying,60,30,30,36,56,50,2,False
296,273,Seedot,Grass,NaN,40,40,50,30,30,30,3,False
346,317,Swalot,Poison,NaN,100,73,83,73,83,55,3,False
446,401,Kricketot,Bug,NaN,37,25,41,25,41,25,4,False
489,441,Chatot,Normal,Flying,76,65,45,92,42,91,4,False

In [29]:
df.loc[df['Name'].str.contains('^pi[a-zA-Z]',flags=re.I, regex=True)].reset_index()#small letters only

,index,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
1,21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
2,22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
3,23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
4,30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False
5,136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False
6,137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
7,186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False
8,219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False
9,239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False
10,438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False
11,558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
12,578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False

In [36]:
df=pd.read_csv('pokemon_data.csv')#Do this in test so changes made above dont carry over
df.loc[df['Type 1']=='Normal', 'Type 1'] = 'unNormal'#changes normal types into unNormal


df.loc[df['Name']=='Pidgey']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,unNormal,Flying,40,45,40,35,35,56,1,False

In [35]:
df.loc[df['Type 1']=='unNormal', 'Type 1'] = 'Normal'#changes it back


df.loc[df['Name']=='Pidgey']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False

In [38]:
df=pd.read_csv('pokemon_data.csv')
df.loc[df['Attack']>100,['Generation','Legendary']] = ['Gen OP','Too OP']#to make changes in values in two saparate columns
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,Gen OP,Too OP
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,Gen OP,Too OP
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,Gen OP,Too OP
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,Gen OP,Too OP

In [39]:
df=pd.read_csv('pokemon_data.csv')

In [44]:
df.groupby(['Type 1']).mean().sort_values('Attack', ascending=False) #mean grouped by type 1

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824

In [41]:
df.groupby(['Type 1']).sum()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Bug,23080,3925,4897,4880,3717,4471,4256,222,0
Dark,14302,2071,2740,2177,2314,2155,2361,125,2
Dragon,15180,2666,3588,2764,3099,2843,2657,124,12
Electric,15994,2631,3040,2917,3961,3243,3718,144,4
Fairy,7642,1260,1046,1117,1335,1440,826,70,1
Fighting,9824,1886,2613,1780,1434,1747,1784,91,0
Fire,17025,3635,4408,3524,4627,3755,3871,167,5
Flying,2711,283,315,265,377,290,410,22,2
Ghost,15568,2062,2361,2598,2539,2447,2059,134,2
Grass,24141,4709,5125,4956,5425,4930,4335,235,3
Ground,11401,2361,3064,2715,1807,2008,2045,101,4
Ice,10165,1728,1746,1714,1861,1831,1523,85,2
Normal,31279,7573,7200,5865,5470,6245,7012,299,2
Poison,7050,1883,2091,1927,1692,1803,1780,71,0
Psychic,21706,4026,4073,3858,5609,4918,4645,193,14
Rock,17280,2876,4086,4435,2787,3321,2460,152,4
Steel,11957,1761,2503,3412,1823,2177,1492,104,4
Water,33946,8071,8305,8170,8379,7898,7388,320,4

In [43]:
df.groupby(['Type 2']).mean()#mean of each column grouped by type 2

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 2,,,,,,,,,
Bug,382.000000,53.333333,90.000000,80.000000,46.666667,61.666667,61.666667,3.333333,0.000000
Dark,413.850000,75.550000,109.800000,72.050000,81.800000,69.850000,75.350000,3.750000,0.050000
Dragon,482.555556,82.166667,94.444444,87.055556,98.500000,83.444444,80.555556,4.166667,0.222222
Electric,465.666667,88.166667,72.666667,68.333333,81.166667,73.500000,71.500000,4.000000,0.166667
Fairy,379.043478,64.304348,61.608696,73.869565,75.000000,81.956522,61.217391,3.565217,0.086957
Fighting,438.192308,79.461538,112.846154,82.500000,81.269231,82.384615,87.384615,3.923077,0.153846
Fire,481.833333,71.250000,81.250000,80.166667,110.416667,83.500000,79.666667,4.000000,0.250000
Flying,331.103093,71.391753,80.288660,68.309278,75.628866,71.206186,85.721649,3.072165,0.134021
Ghost,551.714286,59.142857,84.142857,82.285714,73.214286,78.071429,53.857143,4.785714,0.071429
Grass,505.400000,62.640000,74.160000,80.120000,60.160000,74.520000,57.320000,4.480000,0.000000
Ground,307.600000,77.228571,89.857143,90.314286,65.542857,66.742857,54.657143,2.942857,0.028571
Ice,441.285714,90.000000,98.000000,85.642857,92.642857,84.785714,74.642857,3.714286,0.214286
Normal,681.000000,63.500000,52.750000,53.750000,88.000000,64.250000,89.250000,6.000000,0.000000
Poison,169.970588,58.764706,67.588235,59.558824,74.029412,69.911765,66.647059,1.970588,0.000000
Psychic,337.151515,72.212121,74.696970,87.030303,88.030303,87.606061,69.484848,2.939394,0.151515
Rock,347.785714,68.071429,84.000000,126.857143,51.142857,68.571429,36.000000,3.142857,0.000000
Steel,435.636364,64.636364,92.590909,104.636364,77.727273,86.272727,59.363636,3.818182,0.045455
Water,400.000000,62.714286,70.142857,85.071429,74.500000,68.642857,57.142857,3.428571,0.071429

In [45]:
df=pd.read_csv('pokemon_data.csv')

In [47]:
df['count']=1
df.groupby(['Type 1','Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64