In [2]:
#QUESTION 2 PART A
import pandas as pd
df=pd.read_csv('iris_pt.csv')
df.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [3]:
#QUESTION 2 PART B SUB-QUESTION i
iris_labels=df.pop('Species')
iris_labels

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [4]:
#QUESTION 2 PART B SUB-QUESTION ii
df.drop('Id',axis=1,inplace=True)
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [5]:
#QUESTION 2 PART B SUB-QUESTION iii,iv,v
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df, iris_labels, stratify=iris_labels,test_size=0.30, random_state=3)

In [6]:
#QUESTION 2 PART C SUB QUESTION i,ii
from sklearn.tree import DecisionTreeClassifier 
tree=DecisionTreeClassifier()
tree.fit(X_train , y_train)
print ("Accuracy on training set: {:.2f}".format(tree.score(X_train , y_train)))
print ("Accuracy on test set: {:.2f}".format(tree.score(X_test , y_test)))

Accuracy on training set: 1.00
Accuracy on test set: 0.93

In [32]:
#QUESTION 2 PART D SUB QUESTION i,ii
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train)
print("Accuracy on training set: {:.2f}".format(svc.score(X_train, y_train)))
print("Accuracy on test set: {:.2f}".format(svc.score(X_test, y_test)))

Accuracy on training set: 0.99
Accuracy on test set: 0.96

In [ ]:
#QUESTION 2 PART E 
# I can conclude that SVM model is the best because it has a higher testing accuracy than decision trees model and 
 # where in comparison to decision tree's training accuracy of a perfect 100% which is a sign of overfitting, the SVM model has a very good 
  # but not perfect training accuaracy of 99%.